# Numpy tutorial

## Setup
pip install numpy

## what is numpy
Numpy is one of the main libraries used in machine learning an data science. It os used to manupulate data.

## import to add
import numpy as np 


In [3]:
import numpy as np 
# 1D array 
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [4]:
# shape property: tuple with dimentions
a1.shape

(4,)

In [5]:
# Rank 2 array 
a2 = np.array([[1,2,3,4],
               [5,6,7,8]]) # initialized with a numpy list 
a2 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
a2.shape

(2, 4)

In [7]:
# initilizing matrix
M1 = np.array([[1,0,0], 
               [0,1,0], 
               [0,0,1], 
               [0,0,1]])
M1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1]])

In [8]:
M1.shape

(4, 3)

In [9]:
# Shape is tuple
m = M1.shape[0] # number of rows
n = M1.shape[1] # number of columns 
print(f"m: {m}, n: {n}")

m: 4, n: 3


In [10]:
# reshape: change the dimention of metrix (Note: number of element will remain same)
M2 = np.reshape(M1, (1, 12))
M2

array([[1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1]])

In [12]:
# change flat array into metrix
print(f'shape of a1 = {a1.shape}')
a2 = np.reshape(a1, (a1.shape[0], 1))
print(f'shape of a2 = {a2.shape}')
print(a2)
a3 = np.reshape(a1, (1, a1.shape[0]))
print(f'shape of a3 = {a3.shape}')
print(a3)

shape of a1 = (4,)
shape of a2 = (4, 1)
[[1]
 [2]
 [3]
 [4]]
shape of a3 = (1, 4)
[[1 2 3 4]]


In [13]:
# Note: numpy array are not list
# python list: 
l = [1,2,3,4] 

# np.array 
l_np = np.array(l)

# different print style 
print(l) 
print(l_np) # note the lack of commas 

[1, 2, 3, 4]
[1 2 3 4]


In [14]:
# different behaviour!! 
print(l*5) # multiplying a python list replicates it
print(l_np*5) # numpy applies operation elemntwise

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
[ 5 10 15 20]


In [16]:
# dot: multiplying of 2 metrics and adding them (Note: shape of metrics should be same)
x = np.array([1,9.0,3,4,5.5,6,7,8.9,10]) 
y = np.array([1,10,1,10,1,10,1,11,11]) 
print(x.shape)
print(y.shape)

x = np.reshape(x, (x.shape[0], 1))
y = np.reshape(y, (y.shape[0],1))
print('new shape')
print(x.shape)
print(y.shape)

res = np.dot(x.T,y)
res



(9,)
(9,)
new shape
(9, 1)
(9, 1)


array([[414.4]])

In [17]:
# generating random metrix
M3 = np.random.randn(5,5)
M3 

array([[ 0.75894867, -2.06423193, -0.8324936 , -0.85650213, -2.06443756],
       [ 1.1756937 , -1.42243242,  2.19895677,  0.57867676, -0.48234351],
       [ 0.06038756,  1.59842652, -0.2902028 , -1.36676419, -0.70546483],
       [ 0.58529477,  0.41712251,  2.31557628, -2.49179399,  1.19564577],
       [-0.46782917,  0.17830394, -1.28827019,  0.30467828, -0.13048557]])